---

- name: "3.1.1 | L2 | PATCH | Disable IPv6 | grub"
  replace:
      dest: /etc/default/grub
      regexp: '(^GRUB_CMDLINE_LINUX\s*\=\s*)(?:")(.+)(?<!ipv6.disable=1)(?:")'
      replace: '\1"\2 ipv6.disable=1"'
      follow: yes
  notify: grub2cfg
  when:
      - not rhel7cis_ipv6_required
      - rhel7cis_rule_3_1_1
  tags:
      - level2
      - rule_3.1.1
      - patch

- name: "3.1.2| L1 | Ensure wireless interfaces are disabled"
  block:
      - name: "3.1.2 | L1 | AUDIT | Ensure wireless interfaces are disabled | Check if nmcli command is available"
        shell: rpm -q NetworkManager
        args:
            warn: no
        check_mode: no
        changed_when: no
        register: rhel_07_nmcli_available
        failed_when: no

      - name: "3.1.2 | L1 | PATCH | Ensure wireless interfaces are disabled | Check if wifi is enabled"
        shell: nmcli radio wifi
        register: rhel_07_wifi_enabled
        check_mode: no
        changed_when: rhel_07_wifi_enabled.stdout != "disabled"
        when: rhel_07_nmcli_available.rc == 0

      - name: "3.1.2 | L1 | PATCH | Ensure wireless interfaces are disabled | Disable wifi if enabled"
        command: nmcli radio wifi off
        when: rhel_07_wifi_enabled is changed
  when:
      - rhel7cis_rule_3_1_2
  tags:
      - level1
      - level2
      - rule_3.1.2
